### ISSUE TITLE
I reloaded hero labs and added the 3PP pack, but there are NO Psionic classes showing. I have all of the required core add ons (ACG, Ult Combat, Ult Magic). What am I missing? 

### ISSUE THREAD

**Issue by BlazingDuke** [shadowchemosh/HL-Pack-3PP#14]

**Comment by psych777** [comment]
do you have psionics checked in configure character?
![psionics](https://cloud.githubusercontent.com/assets/10572815/6109770/2be01bf4-b075-11e4-94de-73d9e672f438.jpg)

**Comment by BlazingDuke** [comment]
It's not listed as an option.


Sent from my Verizon Wireless 4G LTE Smartphone

<div>-------- Original message --------</div><div>From: psych777 <notifications@github.com> </div><div>Date:02/09/2015  11:03  (GMT-05:00) </div><div>To: shadowchemosh/HL-Pack-3PP <HL-Pack-3PP@noreply.github.com> </div><div>Cc: BlazingDuke <jjones208@neo.rr.com> </div><div>Subject: Re: [HL-Pack-3PP] I reloaded hero labs and added the 3PP pack, but
  there are NO Psionic classes showing. I have all of the required core add ons
  (ACG, Ult Combat, Ult Magic). What am I missing?  (#14) </div><div>
</div>do you have psionics checked in configure character?

**Comment by psych777** [comment]
What do you have listed in your third party software list? Something has gone wrong if the option isn't there because it should be if you have the 3pp pack installed

**Comment by shadowchemosh** [comment]
The only way that would happen is if you are getting an error on load. So HL has fallen into safe mode. 

If your getting a error on pathfinder load then right click and copy the message and paste it here. 

Thanks

**Comment by BlazingDuke** [comment]
OK. Uninstalled HL again, but I went through and manually deleted a lot of files that were left behind. Reinstalled HL with 3PP and now everything works as it should. Thanks for taking the time to not only create these awesome add-ons, but for taking the time to help me understand how to make them work.

**Comment by shadowchemosh** [comment]
Issue resolved. Closing issue.
