### ISSUE TITLE
Path of War - Archetypes can't chagne Disciplines 

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#15]
http://forums.wolflair.com/showthread.php?p=203430#post203430
Bug report: Archetypes for Path of War are no longer changing the disciplines (Dervish Defender and Zweihand Sentinel).   The add/remove discipline under permanent adjustments also no longer working.

**Comment by IronGolem** [comment]
<a href="https://github.com/shadowchemosh/HL-Pack-3PP/commit/1daf3508cc24f0c32946e214d4d05a5971e3267e">Fixed</a>
