### ISSUE TITLE
Path of War -  Silver Crane or Black Seraph

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#18]
http://forums.wolflair.com/showpost.php?p=203819&postcount=131
the only other issue i have run into is there seems to be no way to add silver crane or black seraph abilities to a path of war character. The pdf says you have to join one of their orders but i do not see that option nor can you just pick one. That one i can fix by going in and just adding their list of maneuvers to all the three classes but I didn't know if there was a better way to do so.

**Comment by IronGolem** [comment]
<a href="http://forums.wolflair.com/newreply.php?do=postreply&t=51966">This can be done through adjustments</a>

**Comment by shadowchemosh** [comment]
Thanks! I totally forgot you added those.  Should have looked before I answered. =)

Will leave this for now as an enhancement note for adding the Martial Traditions down the road.

**Comment by IronGolem** [comment]
Closing this now that Martial Traditions have been implemented
