### ISSUE TITLE
Ultimate Psinoics - Soul Bolt archetype

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#2]
BlazingDuke 
Please add the Soul Knife archetype "Soul Bolt" when you get the time. Thank you so much.

**Comment by IronGolem** [comment]
I'm going to take a whack at this since I've got a Soulbolt character I've been wanting to get into HL forever.  But if anyone else is working on this, let me know so I can put my efforts elsewhere.

**Comment by shadowchemosh** [comment]
TheIronGolem added this archetype in https://github.com/shadowchemosh/HL-Pack-3PP/commit/b3530bb1092e44618596d14a0c01f677f03d8bc0 commit.  Closing out this To-Do.
