### ISSUE TITLE
Path of War - Feat "Extra Readied Maneuver"

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#20]
http://forums.wolflair.com/showpost.php?p=203888&postcount=142

The "Special" wording was added in the final version of this feat allowing it to be taken multiple times.  We need to change its uniqueness and update desc text.

Also I think this is going after the "Classes" array which should be moved over to the "PWManList" component instead I am thinking.

**Comment by IronGolem** [comment]
I'll take a look at this tonight.

**Comment by IronGolem** [comment]
This was fixed in 1.5, closing now
