### ISSUE TITLE
Ultimate Psionics - Enlightened Monk regains bonus feat

### ISSUE THREAD

**Issue by TCArknight** [shadowchemosh/HL-Pack-3PP#21]
When an enlightened monk reaches 2nd level, they now have 2 bonus Monk feats available.

**Comment by psych777** [comment]
was just looking at the monk...are you saying it has 2 but should only have 1 bonus feat? when i first read your notice i thought you were meaning it had 1 and now gets 2....but it currently has 2 bonus feats...

**Comment by TCArknight** [comment]
Actually, the normal monk should get a bonus feat at 1,2,6,10,14,18 I realized I put the adjustments on the actual level on the by level selection, instead of level-1. The Enlightened Monk loses the 1st and 6th level feats. Because I had the adjustments on the wrong level, at 2nd level they gained the 1st and 2nd level at 2nd level.

**Comment by shadowchemosh** [comment]
So is this issue fixed then? Or still to be done?

**Comment by TCArknight** [comment]
This is fixed. 

On 2015-03-01 17:38, Tim Shadow wrote: 

> So is this issue fixed then? Or still to be done? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/shadowchemosh/HL-Pack-3PP/issues/21#issuecomment-76638615
