### ISSUE TITLE
Several issue's when compiling game system date files

### ISSUE THREAD

**Issue by Jamel1027** [shadowchemosh/HL-Pack-3PP#23]
Basically the error states:

![image](https://cloud.githubusercontent.com/assets/11066215/6316921/d747d284-ba7a-11e4-8e7f-56a73f7c2d62.png)

**Comment by IronGolem** [comment]
Are you sure you've pulled down the latest files?  Including those for the Basic Pack?

Those first few errors from ToS are the same ones after I pulled some updates for 3PP but was still behind on the Basic files.  And the last one from PoW should have gone away with a commit I made that removed the extra copy of the ioPWTrvlog thing.

**Comment by Jamel1027** [comment]
Fixed, You were right I didn't have the basic pack from the Github after I updated that it fixed my issues.
