### ISSUE TITLE
Too many Manuevers readied error

### ISSUE THREAD

**Issue by Jamel1027** [shadowchemosh/HL-Pack-3PP#24]
![image](https://cloud.githubusercontent.com/assets/11066215/6317205/924a7d84-ba8a-11e4-91ed-e756e8db2c47.png)

As you can see I have selected 5 out of 5 manuevers and Herolab is kicking back a Validation eror

**Comment by shadowchemosh** [comment]
Issue fixed. So closing out the issue.
