### ISSUE TITLE
how do i change my author username?

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#26]
on the list of commits it has your guys names but mine just says 'unknown'. how can i change that to show psych777?

**Comment by shadowchemosh** [comment]
I see your name phsych777 on everything you do from comments to commits.  Maybe its just a display thing on your side?  Maybe try clearing the browser cache?

**Comment by psych777** [comment]
In sourcetree is where I see it as unknown. On GitHub I don't even see myself as a contributor which really confused me for awhile on whether my commits were actually happening (and that I wasn't screwing up) :o)

**Comment by shadowchemosh** [comment]
Oh yea I see that now.... Hmmm....

**Comment by shadowchemosh** [comment]
In SourceTree go to "<strong>Repository->Add Remote</strong>".  On the new window click on "Origin" and click "edit".  On the new window where it says "User name" does it say "psych777"?

Also try in sourcetree "<strong>Tools->Options</strong>" and on the General tab make sure it has your user information and email setup?

**Comment by psych777** [comment]
Username was there in the origin. Added it to the tools options though. We will see next time I commit if that did it :o)

**Comment by psych777** [comment]
that did it thanks
