### ISSUE TITLE
ALL Classes - Missing "Source Book Information"

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#27]
So I see editors are correctly filling in "Source Page Number" but the "Source Book Information" field does not show in the editor.  You have to manually fill in "srcBookInf" value using the "Fields" blue button at the top right for each class.  Without this the page number info will not display on print outs. =(

So as we get time fill in this info!  Thanks!

**Comment by psych777** [comment]
current ones in psionics should all be done

**Comment by shadowchemosh** [comment]
Sweet. Just leaves PoW and SGG/RGG. I did the ToS ones already.

**Comment by shadowchemosh** [comment]
This issue was moved to shadowchemosh/HL-Pack-Pathfinder#3
