### ISSUE TITLE
Ultimate Psionics - Feat - One Pattern

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#32]
http://forums.wolflair.com/showpost.php?p=205149&postcount=22

Missing feat.  Looks like a new one in UP.

**Comment by psych777** [comment]
i added the feat and did a commit (no push yet). 
after the commit i strangely had a uncommitted changes line. clicking on it it is some stack dump access denied message. i have no idea where this came from or how to safely get rid of it...any ideas?
![image](https://cloud.githubusercontent.com/assets/10572815/6546583/e900b11c-c5b0-11e4-9fd9-a560e857e934.png)

**Comment by shadowchemosh** [comment]
That is strange.  My take is that the file named sh.exe.stackdump is actually in your Pathfinder HL game folder.  So go into the same folder where your .user files are for the 3PP Pack and look for file named "sh.exe.stackdump".  I think you will find it and then move it to your desktop.

**Comment by psych777** [comment]
it was there alright. no idea what happened though as i never even got a popup error.

added feat One Pattern via commit a5d3d96
added eval script to the feat via commit 44833d4
