### ISSUE TITLE
Create Sounds power

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#34]
there was a create sounds 0 and create sounds 1 powers in UP. in my pdf there is only the 0 power one. and when i added create sounds it reduced the number of powers taken by 1. for example, if it was the first power i picked, it would change the power/talent number to -1 power taken, 1 talent taken (since 0 level are Talents). at first i thought this was because of psion being listed in both the 0 and 1 power versions. i deleted the level 1 but the odd number count continued. 
i then found a eval script in the 0 level that reduced the number of powers taken by 1. i commented it out for now and the numbers work. before i deleted it though i wanted to ask if there was a purpose for it being there that i am unaware of?

**Comment by shadowchemosh** [comment]
First is "please" don't ever "delete" anything... Ever!  We need to correctly deprecate the item not delete it.  Deleting a "Thing' can cause HL to not load or cause gamers .por files to toss errors.  Both are these are bad.  We deprecate by "hiding the Thing" and moving it to its own .user file.  The GM Pack already has a file.  So we can create a new one for 3PP called "<strong>COM_3PPPack - Deprecated Things.user</strong>"

The script on the 0 level power is left over from when I was still trying to make "Talents" work correctly before Aaron added new logic to support it.  So removing that is fine.

But please put back the level 1 power.  Lets find out why it exists and if it is a mistake Deprecate it correctly. =)

**Comment by psych777** [comment]
alrighty, sorry bout that.

**Comment by shadowchemosh** [comment]
No issues.  Sorry if the above came across bad.  I am not upset at all.  Just in a hurry as still prepping for my game and players are here in like 15 minutes.

If you have a backup of that "power" please add the Deprecated Things file.  If not I have a back up copy and can do it on Sunday.  Let me know.

Thanks!

And great job on your first Archetype. =)

**Comment by psych777** [comment]
i copied power 0 version and changed it back to the settings power 1 had. looks like the version of herolab adds more verbage to the xml file, but the settings are the same. not sure how to do the move to a new file. 
if my dm hadn't called in sick i'd be playin right now too....sigh...lol
thanks :o)
