### ISSUE TITLE
couple questions...

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#36]
so was starting to go through the feats and came on a couple of questions. the first three are "Ability Focus" (different versions). i did a search of my UP pdf and find no ability focus. are they from a different book?
i've noticed a few items have a Product Identity For... with "Hero Lab Community", but the above ability focus have "Community Created Psionics" for theirs. should we be tagging all of our things with one of these product id's?

**Comment by shadowchemosh** [comment]
The Ability Focus are used to support different Things?  I am not 100% sure myself and its on my list to double check and find out.  Just have not had the time yet to figure out.  I know Frumple has several different ones in use for the GM Pack as some "abilities" that should work with the Ability Focus does not with the LW Core version.

Really everything should have a product tag id of "Hero Lab Community" to match all the other Packs.  "Community Created Psionics" is left over from when the Psionic was separate.  I just have not gotten to doing the mass Find/Replace fo the Psionics one to Hero Lab Community.

**Comment by shadowchemosh** [comment]
All good @psych777 ?  I can close out these questions?

**Comment by psych777** [comment]
sure thing
