### ISSUE TITLE
Ultimate Psionics - Feral Combat training feat

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#39]
Misspell for the Feral Combat training feat:
Feral Conbat Training

**Comment by psych777** [comment]
fixed typo....question...the feat doesn't specifically say it can be taken more than once but it does say you select one of your natural weapons, so does this allow for it to be taken more than once if you have more than one natural weapon? if so, should it have a max limit on it?

**Comment by shadowchemosh** [comment]
Based on the wording I am going with no. You can take the feat only once and only that one natural Attack can be used.

**Comment by psych777** [comment]
okay, updated it
