### ISSUE TITLE
Ultimate Psionics - Gifted Blade Bonus PP

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/HL-Pack-3PP#43]
Gifted Blade does not appear to be receiving bonus PP from WIS.  10th level Elan gifted blade is coming up with 11(base) + 10(Favord Class) + 2  (wild talent) + 2 (naturally psionic) == 25 which is missing the 16 bonus pp from 18 WIS and ML 8

**Comment by psych777** [comment]
strange...i know i tested a wisdom bonus....will have to look at it again as soon as i can

Date: Tue, 31 Mar 2015 18:49:51 -0700

**Comment by psych777** [comment]
seem to have it adding in now, but is still miscalculating, partly due to the other bug posted concerning the manifester level not applying properly

**Comment by psych777** [comment]
this should be working correctly
