### ISSUE TITLE
question regarding wild talent vs psionic talent

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#44]
so pretty much every psionic race has the Naturally Psionic feature stating:

*Race gain the Wild Talent feat as a bonus feat at 1st level. If a *race* takes levels in a psionic class, he instead gains the Psionic Talent feat.*

so basically if they use any of the classes in the UP (which are said to be psionic) then the race changes the wild talent to psionic talent.

but one class (soulknife) also gets Wild Talent as a class feature at first level:

*Wild Talent: The soulknife gains Wild Talent as a bonus feat at 1st level. This provides his with the psionic power necessary to manifest his mind blade. A character who is already psionic instead gains the Psionic Talent feat.*

so, the wording makes it sounds like both Wild Talent's (from race and class) are instead changed to Psionic Talent. 
of course, Psionic Talent *CAN* be taken multiple times. (*Special: You can take this feat multiple times. Each time you take the feat after the first time, the number of power points you gain increases by 1.*)

so....
1. does this mean a Soulknife with a psionic race should have no Wild Talent feat and have 2 Psionic Talent feats?
2. if yes to 2 Psionic Talent feats, would the first one give 2 power points and the second 3 power points for a total of 5 (per the *special* noted above of the 1 pp increase per time feat taken)?

**Comment by IronGolem** [comment]
It's a good question, and I think the answer depends on whether the Soulknife counts as a "psionic" class.  That may seem like a no-brainer, but bear in mind that the class can't manifest powers and doesn't grant a power point reserve (the Gifted Blade archetype notwithstanding).  It does grant a bonus feat that gives power points, but the distinction of "power points as a class feature" vs "power points as the benefit of a feat GRANTED by a class feature" might make all the difference.

Ever notice how doing this stuff forces you to be a total rules lawyer?

Anyway, I'd pose the question to DSP if I were you.  I couldn't find a definitive answer myself.  Though I can say with confidence that if you do end up with two Psionic Talent feats, then the second one does gain the increased benefit as you describe.

**Comment by psych777** [comment]
according to the book it is a psionic base class:

*The ten psionic base classes, in the order they are presented in this chapter, are as follows.
Aegis
Cryptic
Dread
Marksman
Psion
Psychic Warrior
Soulknife
Tactician
Vitalist
Wilder*
page 26

**Comment by shadowchemosh** [comment]
I know I had this working at one time.  A soulknife should get both the Wild Talent and Psionic Talent feat as either from the race or class he becomes a psionic character because he has psionic points.

This appears to no longer be working correctly. =(

**Comment by psych777** [comment]
Yeah my soul knife I can see tags for a soul knife wild talent and 2 normal wild talent when I used the élan race (was testing same race as the bug poster to test)

**Comment by shadowchemosh** [comment]
I also just found that Psionic Talent does not work either.  Sigh...

**Comment by shadowchemosh** [comment]
So I am going to be making changes to these sections right now.  So can you "not" makes changes.  This we we don't have any merge issues again. =)

This is actually really strange in the way it loops around in the logic.

**Comment by shadowchemosh** [comment]
I think I have this fixed. Anyone else want to give it a try?

**Comment by psych777** [comment]
i would but i've just got online, and i'm fallin asleep at the keybord as its after midnite here...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
and i've fallen asleep 3 times just trying to type that...

**Comment by psych777** [comment]
seems to be working right (since you obviously are on the side of the fence that Wild Talent does stay in place hehe). i see you have psionic talent adding only 1 pp on additional takings of the feat. is it really only 1? i guess the description could be read that way but i was reading it as the first time you took it it gave you 2 pp, the second time it gave an additional 3 pp (so total additional pp by both takings of the feat would be 5 pp), the third time an additional 4 pp (for total bonus 9 pp).... 
seems to really be useless to use up a feat for a single pp which is why i was reading the text the way i was.
so you don't have to look it up here is the text:
*Benefit: When you take this feat for the first time, you gain 2 power points.
Special: You can take this feat multiple times. Each time you take the feat after the first time, the number of power points you gain increases by 1.*

ps. your 'i'm going to edit...so can you not make changes' message cracked me up :o)

**Comment by shadowchemosh** [comment]
You appear to be correct sir for psionic talent.  I read that description text too fast.  It indeed should be giving an extra 1 per feat taken.  So first time is 2, 2nd time is 3, third time is 4.  I will fix that.  Good catch!  This is the other nice thing about having more people around. =)

I am on the side that for a Soulknife its the "Wild Talent" he is getting that is causing him to become Psionic.  I know some of the text says "psionic class" but I really think based on reading that they mean a Psionic Character (from a class, race, or taking Wild Talent).  Which in this case Wild Talent is given by the race making them a Psionic Character.  So the Soulknife class ability is should give them Psionic Talent.

So by logic something has to happen first.  So I set the "Race" first giving them to be Psionic and then the class is taken and says "hey we are Psionic give 2 extra points".

Something to test is that this all works correctly if I just take the "Wild Talent" feat at 1st level????

**Comment by psych777** [comment]
honestly i didn't know which way that would go as it really could have been read either way! :o)
i mean on one hand it makes sense that one of them stays as wild talent, its just the wording they use makes it sound like they both upgrade to psionic talent.
hmm...well wild talent is something can only be taken once right? if the race has given it as a bonus then shouldn't be selectable in feat selection right? or are you guessing someone will pick the feat before choosing their race?

Date: Fri, 3 Apr 2015 13:03:21 -0700

**Comment by shadowchemosh** [comment]
<strong>hmm...well wild talent is something can only be taken once right? if the race has given it as a bonus then shouldn't be selectable in feat selection right? or are you guessing someone will pick the feat before choosing their race?</strong>

Correct about taking it only once.  I am more thinking about I take "Human" and then take 'Wild Talent' then Soulknife should give the "Psionic Talent".  Hmm need to test/check that.  I am not super happy with how I have this codded.

**Comment by shadowchemosh** [comment]
Leaving this here as  note for how to fix Psionic Talent:

Remove new 'ability' thing and put script logic back on to the Psionic Talent:
[code]
~ If we're disabled, do nothing
doneif (tagis[Helper.FtDisable] <> 0)

~ Total up the number of PP this feat should give. We are counting our self so we give 1 plus
~ the number of additional times this feat has been taken.
field[abValue].value += 1 + hero.tagcount[Ability.fPUPsiTal]
#resmax[resPowerPt] += field[abValue].value
[/code]

**Comment by shadowchemosh** [comment]
Closing. Lets move discussion to the forums instead.  Easier to work with and no one forgets to "close" out the question when done. =)
http://forums.wolflair.com/showthread.php?t=51777
