### ISSUE TITLE
manifester level

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#45]
okay, i can not figure out how the manifester tag is getting assigned. i assume each tag is calculated to give a manifester level as each level adds another Hero.Manifester tag, i just can't figure out how it is adding the tag.
and does the manifester level show on the character portfolio anywhere? if it does i must be blind because i can't see it!

**Comment by shadowchemosh** [comment]
I am pretty sure the Hero.Manifester is being applied by a background component.  So you won't see it.  I would think the ML value would be store on the Class Helper where CL is stored.  But I have not looked in awhile nor have access here at work.

**Comment by shadowchemosh** [comment]
So looks like CL is the same ML on Psionic Classes.  So ML is stored as hero.child[cHelpXXX].field[cCasterLev].value where "XXX" is the three digit class id.

**Comment by psych777** [comment]
excellent, thanks

**Comment by psych777** [comment]
so where can i 'see' the caster level? i don't see it in Totals and i can't seem to find a selection fields option that i can think of to show it. 
tried to affect it with a script but nothing is changing like i expect so wanted to see if it was really reducing the levels or not

**Comment by shadowchemosh** [comment]
hero.child[cHelpXXX].field[cCasterLev].value

So if you add the Psion Class.  Then go to look for Fields on Picks.  Then you want the Psion Class Helper Object cHelpPsi or cHelpPSN?  I don't remember the ID but Class Helper Objects always start with "cHelp".

**Comment by psych777** [comment]
thanks, found it. the script i have is reducing the caster level, but its still not affecting the bonus pp from the wisdom bonus per manifester level. if i understand that right he shouldn't get any bonus pp's from wisdom bonus until he has a manifester level, which at character level 3 is manifester level 1...but i'm still earning bonus pp's at level 1 from wisdom score... other than writing a script to determine wis bonus and then subtracting that amount from the total for the first two levels...not sure where to go...any ideas on something easier? or am i just totally reading the bonus wrong?

Date: Fri, 3 Apr 2015 12:56:38 -0700

**Comment by shadowchemosh** [comment]
A) I am not sure if HL is reading the Hero.Manifester tags to figure out ML or using the Class Helper Field.  If the Class does not get PP or ML until level three then it should not have Tags saying the class is a Psionic Class until level three.  That would most likely need a script.

Can you tell me what your trying to accomplish (which rule) that would make it easier for me to find you the best way to go.

**Comment by psych777** [comment]
gifted blade text:Gifted BladeThere are some soulknives who learn to manifest powers, as well as to form mind blades. These gifted individuals wield both blade and mind with deadly efficiency Manifesting: At 3rd level, a gifted blade gains the ability to manifest a small number of psionic powers, which are drawn from the gifted blade power list. 
bonus pp's from wisdomAbilities And ManifestersThe ability that your powers depend on—your key ability score as a manifester—is related to what psionic class (or classes) you have levels in: Intelligence (psion), Wisdom (psychic warrior), and Charisma (wilder). The modifier for this ability is referred to as your key ability modifier. If your character’s key ability score is 9 or lower, you can’t manifest powers from that class. Just as a high Intelligence score grants bonus spells to a wizard and a high Wisdom score grants bonus spells to a cleric, a character who manifests powers (psions, psychic warriors, and the like) gains bonus power points according to his key ability score. Refer to Table 2-1: Ability Modifiers and Bonus Power Points.How To Determine Bonus Power Points: Your key ability score grants you additional power points equal to your key ability modifier × your manifester level ×½. Table 2-1: Ability Modifiers and Bonus Power Points shows these calculations for class levels 1st through 20th and key ability scores from 10 to 41. For multiclass characters, calculate bonus power points for each class individually and add all bonus power points gained to your power point pool.
currently as soon as you give the soulknife the archetype a manifester tag is applied, and another one for each level of soulknife added. hmm. if have a script that says if soulknife level is less than three to delete the manifester tag, when the 3rd level gets added will it still add just one tag or will it add the 2 removed ones back again?
Date: Fri, 3 Apr 2015 14:38:10 -0700

**Comment by psych777** [comment]
well...wanted to test removing manifester tag would even affect the wisdom bonus...got it to remove the tag in final phase, but the wis pp bonus is still being applied...

**Comment by shadowchemosh** [comment]
So after much trial/error I found tracked down the timing that the cMagicLev & cCasterLev & Hero.Manifester are being set at <strong>Post-Attributes/10000</strong>.  Though changing these values does strange stuff....  Still looking.

**Comment by shadowchemosh** [comment]
So yikes that was "FUN" and took a few hours of work.  Yea HL really does not like having its ML value adjusted.  I will commit and push my final version so you can test it out.  I added this script onto a new class feature that I attached to the archetype.  I tested the ML value getting set on the powers and tested that the final PP value is correct.  Please keep in mind the soulknife gets the Psionic Talent feat at level three because it is a full Psionic Hero.  So don't forget to add in the 2PP from the feat.

Here is the script logic:
```
    <eval phase="First" priority="1500" index="1"><![CDATA[
      ~we're earlier than the normal test for whether we've reached the correct level, so we'll recreate that test here
      doneif (root.linkage[varies].field[cTotalLev].value + field[xExtraLev].value + field[xEffectLev].value < tagvalue[ClSpecWhen.?])
      ~ If we've been Disabled, get out now
      doneif (tagis[Helper.SpcDisable] <> 0)    
    
      ~ Set hero.Psionic as at this level we are now a full Psionic Character with a ML
      call SetHeroPsi
      ]]></eval>

    <eval phase="PostAttr" priority="10001" index="2"><![CDATA[
      ~ If we're not shown, just get out now
      doneif (tagis[Helper.ShowSpec] <> 1)
      ~ If we've been Disabled, get out now
      doneif (tagis[Helper.SpcDisable] <> 0)    
      ~ If we have our ML adjustment level is zero then, get out now
      doneif (field[abValue].value = 0)    

      ~ NOTES on abValue Fields:
      ~ abValue - Holds the amount to adjust the ML. If zero 
      ~           this script does not run
      ~ abValue2 - Holds the calculated value for the number of 
      ~            Hero.Manifester tags to put back on the hero.
      var iX as number
      var PP as number

      ~ CHANGE CLASS VALUES
      ~-------------------------------
    
      ~ Check to see if we are bootstrapped to an Archetype?
      if (root.islinkage[varies] <> 0) then
        ~ Adjust our archetype ML field values down by 2
        root.linkage[varies].field[cMagicLev].value += field[abValue].value
        root.linkage[varies].field[cCasterLev].value += field[abValue].value
      ~..We are bootstrapped directly to a class
      else
        ~ Adjust our class ML field values down by 2
        root.field[cMagicLev].value += field[abValue].value
        root.field[cCasterLev].value += field[abValue].value    
      endif

      ~ CHANGE HERO TAGS
      ~-------------------------------

      ~ Count number of Manifester tags and then subtract out two of them. We
      ~ Need to know how many tags to put back on to the hero as delete[] removes
      ~ all tags and we just wish to remove 2.
      field[abValue2].value += hero.tagcount[Hero.Manifester] + field[abValue].value
      perform hero.delete[Hero.Manifester]
      perform hero.delete[Psionics.Class]

      ~ Loop and apply our adjusted number of Manifester tags back to hero
      while (iX < field[abValue2].value)
        iX += 1
        perform hero.assign[Hero.Manifester]
        perform hero.assign[Psionics.Class]
      loop

      ~ CHANGE POWER POINT SESERVE
      ~-------------------------------

      perform hero.findchild[BaseAttr,root.tagids[PsiAttr.?]].setfocus
      ~ If setfocus failed then get out now!
      doneif (state.isfocus = 0)

      ~ HL still calculated our PP attribute bonus using our full level
      ~ so we need to re-calculate the value and then remove it.
      PP = focus.field[aModBonus].value * root.linkage[varies].field[cTotalLev].value * .5
      PP = round(PP,0,-1)
      #resmax[resPowerPt] -= PP

      ~ Calculate our correct PP Reserve for our current ML add it to our
      ~ Power Point Reserve total.
      PP = focus.field[aModBonus].value * root.linkage[varies].field[cMagicLev].value * .5
      PP = round(PP,0,-1)
      #resmax[resPowerPt] += PP     
      ]]></eval>
```

**Comment by psych777** [comment]
wow, quite complex. 
i'm working on rebuilding my cheatsheet for what the PP's should be when i level as i accidentally left it at last hotel, but just a quick check seemed to show problem of wis mod per manifester lvl still adding bonus pp at levels 1 and 2, as the manifester tags were created at level 1 and 2, then 3rd level deleted them and added 1 back in (expected to have one).
or is the manifester supposed to be there if i have a psionic race such as Elan...which is what i've been testing with...will have to check on that too...

**Comment by psych777** [comment]
ok wierd...second time i made the same elan char and no manifester tag at 1st level...will keep on..

**Comment by psych777** [comment]
oh weird...so at manifester level 1, the first bonus PP from wisdom occurs at a 14 Wis. so that char showed no manifester tag but as soon as i bumped the wisdom up to 14 a bonus PP showed up and i checked the tags again and now there is a manifester tag..

**Comment by shadowchemosh** [comment]
Sigh I admit I forgot to test much before level 3.  All my testing was done at level 3+....

**Comment by psych777** [comment]
hehe, okay here is what i see. it looks like 3+ is doing good (once we fix psionic talent to add 3 pts on the second feat instead of the current 1). 
first and second level are getting manifester tags as soon as the wisdom score hits 14 and its adding the wis bonus to pp.
![image](https://cloud.githubusercontent.com/assets/10572815/6998984/7c0f675e-dbec-11e4-9875-544d7cb48b89.png)

**Comment by shadowchemosh** [comment]
I think I have it!  Yeah!  Thanks for the help.  I am committing now.  See if that is better.  I tested now the lower levels, with a 10-18 Wis, and with and without the Elan race.  Its looking like the right numbers now. =)

**Comment by psych777** [comment]
seems to have done it! thanks for the help, i don't think i'd ever have come up with that coding, at least not for a few years. haha

**Comment by shadowchemosh** [comment]
Closing. Lets move discussion to the forums instead.  Easier to work with and no one forgets to "close" out the question when done. =)
http://forums.wolflair.com/showthread.php?t=51777
