### ISSUE TITLE
PathOfWarEx - Dark Messenger: Helper.ShowSpec not working?

### ISSUE THREAD

**Issue by IronGolem** [shadowchemosh/HL-Pack-3PP#49]
Not sure why, but this bit of code that we always (are supposed to) put on class specials:

`doneif (tagis[Helper.ShowSpec] = 0)`

is always firing on Dark Messenger, stopping the script from doing anything.  The tag IS getting applied to the ability, so I don't know what's happening.  I've commented it out in my [commit](https://github.com/shadowchemosh/HL-Pack-3PP/commit/a45d573d1cc238c24cca0c25e30a83aade18d586), but I'd like to get some more eyes on this to see what I'm missing.  Maybe it's a timing issue since I need these scripts to run fairly early, but I could *swear* that I've seen this work on other things as early as First/500.

**Comment by shadowchemosh** [comment]
Sorry this totally slipped my mind.

So Helper.ShowSpec only is applied at about Post-Level/100 ish?  This is why Class Specials almost always run at Post-Level/10000 or higher.

So in this case you can run the following code.  But to be honest I have never tried running as early as First/500.  I am not sure even this logic works that early:
<code>
~we're earlier than the normal test for whether we've reached the correct level, so we'll recreate that test here
</code>
<code>
doneif (root.linkage[varies].field[cTotalLev].value + field[xExtraLev].value + field[xEffectLev].value < tagvalue[ClSpecWhen.?])
</code>

Try adding this test instead and see if it works.....
