### ISSUE TITLE
Path of War - Warlord

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#51]
From an email:

That said, I think I may have run across a small bug while playing the PoW's Warlord. On level 3 he gains the class feature 'Warleader', which among other things grants the warlord a bonus teamwork feat. Herolab does not add the extra feat.

**Comment by shadowchemosh** [comment]
Additional issue:
I just noticed that the Warlord's Force of Personality does not seem to add the character's charisma modifier to his will save as intended.

**Comment by IronGolem** [comment]
Warlord seems to be missing a fair bit; I must have forgotten to do a post-release pass on it after PoW was finalized.  Going through it now.

**Comment by IronGolem** [comment]
[Fixed in this commit](https://github.com/shadowchemosh/HL-Pack-3PP/commit/e8461ea22134a9aaeb154a6dd347395b77b12f80)
