### ISSUE TITLE
Extra Power Known feat

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#53]
looks like the feat is in there twice. or am i misreading something?

**Comment by shadowchemosh** [comment]
Corecct fPUExSpKno is the extra feat and has no coding.  So lets move it to the "deprecated" file copy/pasting in XML.  And set it to be hidden.  I don't know how long its been out in the files so we can't just delete it now.

Closing. Lets move discussion to the forums instead.  Easier to work with and no one forgets to "close" out the question when done. =)
http://forums.wolflair.com/showthread.php?t=51777
