### ISSUE TITLE
Path of War - feat discipline focus

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#54]
http://forums.wolflair.com/showpost.php?p=209753&postcount=326

I found a bug. The feat discipline focus isn't counting the cursed razor maneuvers.

**Comment by IronGolem** [comment]
[Fixed](https://github.com/shadowchemosh/HL-Pack-3PP/commit/5080eaf3a6949393c54157d76b278af637b26d32)
