### ISSUE TITLE
greater psionic fist feat

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#58]
just trying to see if i'm missing something somewhere. the eval script for this feat says:
      ~ Increase damage of Psionic Fist feat
      #value[fPUPsiFist] += field[abValue].value
      #value2[fPUPsiFist] += field[abValue2].value
      #value3[fPUPsiFist] += field[abValue3].value

the feat "Fields" have a abValue and abValue2 entries, but i see nothing for abValue3. am i just missing it somewhere?

**Comment by shadowchemosh** [comment]
abValue3 on FPUPsiFist is the Dice Size (ie d6).  So I coded in abValue3 into Greater so that encase anyone sets a value into abValue3 it moves to fPUPsiFist.  Otherwise by default it will be zero and zero added to anything will be the same value.  So no harm in future planning. =)

**Comment by shadowchemosh** [comment]
Closing. Lets move discussion to the forums instead.  Easier to work with and no one forgets to "close" out the question when done. =)
http://forums.wolflair.com/showthread.php?t=51777
