### ISSUE TITLE
alternate racial traits for Blue getting error

### ISSUE THREAD

**Issue by psych777** [shadowchemosh/HL-Pack-3PP#61]
I'm getting the following error with the 'Blue' race in Ultimate Psionics when trying to add the alternate Racial trait of 'Goblinoid Camoflage', 'Kinslayer' and 'Psionic Prodigy'.

Tag group 'AbReplace' does not possess tag 'raBlueRepl' that is copied from group 'RaReplace'
Location: 'eval' script for Component 'CanRepRaAb' (Eval Script 'Forward RaReplace') near line 21

**Comment by psych777** [comment]
it looks like there may have been a raBlueRepl at one time maybe? the only 'Repletion' racial trait right now has 'Elan' in the description, and the Elan race also does have Repletion trait. should this trait have 2 separate entries, 1 for each race?

**Comment by delawless** [comment]
The Repletion racial trait applies to both races.  I don’t think you need two entries (one for blue, one for Elan).

**Comment by shadowchemosh** [comment]
You can have an ART go to two different races as along as the abilities replaced are the EXACT same Thing on each race. (ie are the exact same Unique ID).  These where changed at one point and no one updated the ART's would be my take.

I am going to assume no one is around so going to do a mass find/replace to fix.....

**Comment by psych777** [comment]
the only reason i thought that there were separate ones before was because the current Repletion says "Elan" in the description. so someone playing a Blue char might later report a bug that Repletion says "Elan" instead of "Blue" in the text description

Date: Sun, 28 Jun 2015 09:47:25 -0700
