### ISSUE TITLE
Ultimate Psionics - Aberrant Aegis 'transformed' not activating Customizations

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/HL-Pack-3PP#75]
Aberrant Aegis when the 'transformed' state is checked has the following issues:
Does not apply the DR from the base Aegis.
Does not apply the enhancement bonus to STR from Brawn.  This also applies to Dex from Nimble and CON from Hardy.  Evasion likewise does not appear when transformed if that customization is selected.

**Comment by shadowchemosh** [comment]
This issue was moved to shadowchemosh/HL-Pack-Pathfinder#15
