### ISSUE TITLE
Path of War - Not Implemented Feats

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#8]
Not implemented (specifically, those things I want to use for this character - Umbral Blade PrC; Steel Serpent discipline; Defensive Expertise, Martial Training, and Serene Stride feats.

**Comment by shadowchemosh** [comment]
IronGolem
Steel Serpent, Defensive Expertise, and Serene Stride are implemented now

**Comment by shadowchemosh** [comment]
IronGolem
Martial Training is now implemented

**Comment by IronGolem** [comment]
Closing this because all of these items are now implemented
