### ISSUE TITLE
Ultimate Psionics PrC - To Do List

### ISSUE THREAD

**Issue by delawless** [shadowchemosh/HL-Pack-3PP#80]
For tracking purposes:

__Prestige Classes to be added__

Adaptive Warrior
Body Snatcher
Dark Tempest
Metamorph
Mystic Archer
Psicrystal Imprinter
Sighted Seeker
Telekinetic Weaponmaster

**Comment by shadowchemosh** [comment]
This issue was moved to shadowchemosh/HL-Pack-Pathfinder#19
