### ISSUE TITLE
Ultimate Psionics - Unwilling Participant feat has no DC

### ISSUE THREAD

**Issue by delawless** [shadowchemosh/HL-Pack-3PP#82]
The DC for the Unwilling Participant feat should be (DC 10 + half manifester level
+ Wisdom modifier) -- currently does not calculate a DC.

**Comment by psych777** [comment]
lol we were working on this at the exact same time! i refreshed remote repos and had no pulls. made edits, when to sourcetree and there were now 2 pulls! 

Date: Sun, 24 Jan 2016 15:27:44 -0800
