### ISSUE TITLE
Favored Class Option: Elan, Cryptic: +1/2 to disrupt pattern damage not functioning

### ISSUE THREAD

**Issue by delawless** [shadowchemosh/HL-Pack-3PP#88]
Not currently functioning.  Only +1 PP and +1 HP/Sk options  in list.

**Comment by delawless** [comment]
This issue looks to be larger than initially thought.  It seems to be an intermittent issue, it seems to apply only to some TCOs, not all, all with the same timing.

**Comment by shadowchemosh** [comment]
Hmmm  Thats strange...

Will take a look as soon as I can..

**Comment by shadowchemosh** [comment]
This issue was moved to shadowchemosh/HL-Pack-Pathfinder#22
