### ISSUE TITLE
Ultimate Psionics - Emulate Melee Weapon

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-3PP#9]
Emulate Melee Weapon - Debating on whether this should have a user text box to type wpn or select melee weapon from dropdown list (but then would have to add that weapon on char in order to show up in the list)

**Comment by psych777** [comment]
any thoughts on which option to go with? the text box seems easiest and most fluid. 
but i started to wonder, does this blade skill mean that the emulated weapon has the stats (dmg and whatnot) of the selected weapon or still the stats of the mindblade? if it had the stats of the chosen weapon, it seemed best to have them add the weapon to their char to have all the stats of the weapon and then it could be selected in a drop down on the blade skill

**Comment by shadowchemosh** [comment]
The text says "<strong>and it functions in all ways as the chosen weapon.</strong>"  So I am leaning towards the fact that the weapon does damage and even crit values as the weapon chosen.  In which case we need the ability of Mind Blade weapon to inherit the properties of the weapon chosen.

The only down side is the ability to take more than once.  So we need a non-unique Generic Mindblade that can be added to the hero multiple times.  Then have the gamer select both the Generic Mindblade that will get the values and the "real" weapon we will act like.

This is not impossible but will take me some time to implement actually.  Which I just don't have the time for right now.  Unless you want to give this a try psych777?

**Comment by psych777** [comment]
i will take a stab at it when i have a chance...

Date: Sun, 15 Feb 2015 11:24:56 -0800

**Comment by shadowchemosh** [comment]
Closing. Lets move discussion to the forums instead.  Easier to work with and no one forgets to "close" out the question when done. =)
http://forums.wolflair.com/showthread.php?t=51777
